In [1]:
import numpy as np

# Pair Numpy
Creación y Indexación:

In [3]:
# Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

a1 = np.random.randint(10,100, (50))
a1

array([13, 81, 82, 82, 11, 90, 69, 57, 22, 75, 41, 41, 98, 61, 39, 84, 62,
       80, 25, 50, 84, 49, 15, 91, 10, 71, 52, 53, 37, 33, 98, 22, 56, 16,
       79, 58, 97, 69, 99, 11, 35, 36, 73, 29, 83, 51, 96, 53, 99, 77],
      dtype=int32)

In [4]:
a1[5::5]

array([90, 41, 84, 84, 71, 98, 58, 35, 51], dtype=int32)

In [5]:
# Crea un array 1D con 30 valores aleatorios del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

a2 = np.random.randint(1, 21,(30))
a2


array([ 1, 17,  9, 16,  8,  4,  1,  4, 14, 19, 10, 13, 12,  5,  8,  6, 19,
       11,  5,  6, 12,  3,  6,  1,  4,  2,  3,  2, 10,  8], dtype=int32)

In [6]:
a2[1::2]

array([17, 16,  4,  4, 19, 13,  5,  6, 11,  6,  3,  1,  2,  2,  8],
      dtype=int32)

In [7]:
# Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1).
# Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.
a3 = np.random.uniform(2.00,3.00,(4,6))
a3

array([[2.13713164, 2.9474553 , 2.90097211, 2.5375275 , 2.28783397,
        2.278158  ],
       [2.0024613 , 2.15820682, 2.43906448, 2.64821817, 2.84114863,
        2.50956451],
       [2.42064045, 2.02921345, 2.552818  , 2.73690323, 2.41626617,
        2.36599856],
       [2.45630597, 2.74504191, 2.54697698, 2.00033261, 2.81586232,
        2.45062016]])

In [8]:
a3[-1]

array([2.45630597, 2.74504191, 2.54697698, 2.00033261, 2.81586232,
       2.45062016])

In [9]:
a3r = np.round(a3, decimals=2)
a3r

array([[2.14, 2.95, 2.9 , 2.54, 2.29, 2.28],
       [2.  , 2.16, 2.44, 2.65, 2.84, 2.51],
       [2.42, 2.03, 2.55, 2.74, 2.42, 2.37],
       [2.46, 2.75, 2.55, 2.  , 2.82, 2.45]])

In [10]:
a3r[-1]

array([2.46, 2.75, 2.55, 2.  , 2.82, 2.45])

Funciones Aritméticas y Estadísticas:

In [11]:
# Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

a4r = np.round(np.random.rand(2,3,5), decimals=1)
a4r


array([[[0.9, 0.9, 0.6, 0.8, 0.7],
        [0.2, 0. , 0.1, 0.7, 0.5],
        [0.6, 0.9, 0.4, 0.4, 0.4]],

       [[0. , 0.5, 0.5, 0.2, 0.3],
        [0.7, 0.3, 0. , 0.1, 0.7],
        [0.5, 0.6, 0.6, 0.9, 0.5]]])

In [12]:
a4r.ndim

3

Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. 
Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:

- Si el valor del array es igual que la media, se reemplaza por "A".
- Si el valor del array es mayor que la media, se reemplaza por "B".
- Si el valor del array es menor que la media, se reemplaza por "C".
- Si el valor es igual que el máximo, se reemplaza por "D".
- Si el valor es igual que el mínimo, se reemplaza por "E".

In [13]:
a5 = np.empty((2,3,5))
a5

array([[[0.9, 0.9, 0.6, 0.8, 0.7],
        [0.2, 0. , 0.1, 0.7, 0.5],
        [0.6, 0.9, 0.4, 0.4, 0.4]],

       [[0. , 0.5, 0.5, 0.2, 0.3],
        [0.7, 0.3, 0. , 0.1, 0.7],
        [0.5, 0.6, 0.6, 0.9, 0.5]]])

In [30]:
media_redondeada = round(np.mean(a5), 0)  # Usamos un valor entero para simplificar la comparación
valor_max = np.max(a5)
valor_min = np.min(a5)

In [31]:
# Array inicial para las letras (debe ser de tipo string)
array_letras = a5.astype(str)

In [32]:
# 1. Asignar el valor MÁXIMO ("D") y el resto permanece igual.
# Si la condición es Falsa, mantiene el array_letras original.
array_letras = np.where(a5 == valor_max, "D", array_letras)

# 2. Asignar el valor MÍNIMO ("E")
# Si la condición es Falsa, mantiene el resultado del paso 1.
array_letras = np.where(a5 == valor_min, "E", array_letras)

# 3. Asignar la MEDIA ("A")
# Si la condición es Falsa, mantiene el resultado del paso 2.
array_letras = np.where(a5 == media_redondeada, "A", array_letras)

# 4. Asignar Mayor que la media ("B")
# Si la condición es Falsa, mantiene el resultado del paso 3.
array_letras = np.where(a5 > media_redondeada, "B", array_letras)

# 5. Asignar Menor que la media ("C")
# Ya que todas las condiciones anteriores se han verificado, la única opción restante
# para los valores que aún no han sido sustituidos es que sean menores que la media,
# pero lo haremos explícitamente para mayor claridad.
array_letras = np.where(a5 < media_redondeada, "C", array_letras)

In [33]:
array_letras

array([[['B', 'B', 'B', 'B', 'B'],
        ['B', 'A', 'B', 'B', 'B'],
        ['B', 'B', 'B', 'B', 'B']],

       [['A', 'B', 'B', 'B', 'B'],
        ['B', 'B', 'A', 'B', 'B'],
        ['B', 'B', 'B', 'B', 'B']]], dtype='<U32')

In [ ]:
# a modo de ejemplo. Si tenemos el siguiente array
[[[0.4, 0.7, 0.2, 0.9, 0.2],
    [0.1, 0.9, 0.6, 0.1, 0.2],
    [1. , 0.2, 0.1, 0.8, 0.3]],

[[0. , 0.3, 0.4, 0.5, 0.1],
    [0.5, 0.7, 0.9, 0. , 0.8],
    [0.5, 0.3, 0.5, 0.8, 0.1]]])

# sabiendo que la media es 0.4 y el máximo es 1.0 y el mínimo es 0.0

# nuestro array vacío debería quedar como este: 
[[["A", "B", "C", "B", "C"],
    ["C", "B", "B", "C", "C"],
    ["D" , "C", "C", "B", "C"]],

[["E" , "C", "A", "B", "C"],
    ["B", "B","B", "E" , "B"],
    ["B", "C", "B", "B", "C"]]])

Si te queda tiempo, puedes hacer los siguientes ejercicios:
Crea un array 3D de forma (2, 3, 5) y 30 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 61 (sin incluir). Utiliza reshape para convertirlo en un array 2D.

Utiliza el array 3D del ejercicio anterior de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).

Utiliza el array 3D del ejercicio anterior 3 de reshape. Utiliza transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 5, 4).